name: Java CI with Maven

on:
  push:
    branches: [ "main-v2" ]
  pull_request:
    branches: [ "main-v2" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -DskipTests clean package

    - uses: actions/upload-artifact@v4
      with:
        name: java-war-file
        path: target/spring-application-*.war

  code-quality:
    runs-on: ubuntu-latest
    if: false
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0

    - name: Set up JDK 11 (required)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Java-Practice-App-v2
        
  test:
    needs: ['code-quality', 'build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Test with Maven
      run: mvn test

  deploy-A:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: java-war-file
      
    - name: copy WAR file to Tomcat Webapps folder
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.HOST_A }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "target/spring-application-*.war"
        target: "/var/lib/tomcat9/webapps/ROOT.war"

  deploy-B:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: java-war-file
      
    - name: copy WAR file to Tomcat Webapps folder
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ vars.HOST_B }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "target/spring-application-*.war"
        target: "/var/lib/tomcat9/webapps/ROOT.war"

